name: fastapi-ci

on:
  push:
    path:
      - 'fastapi-streamlit-lab/fastapi/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        id: commit
        uses: pr-mpt/actions-commit-hash@v2
      -
        name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # TODO: change to your python version
      -
        name: Install pipenv
        run: pip install pipenv
      -
        name: Run tests
        working-directory: ./fastapi-streamlit-lab/fastapi # TODO: change to your pytest path
        run: |
          pipenv install -r requirements.txt 
          pipenv run pytest -v
        
